/**
 * Example Integration: GenerationHistory with Block Editor
 * 
 * This example demonstrates how to integrate the GenerationHistory component
 * with a block editor to enable content reuse from previous generations.
 */

import React, { useState } from 'react';
import { GenerationHistory, GenerationHistoryEntry } from './GenerationHistory';
import { AIAssistantPanel } from './AIAssistantPanel';
import { CourseContext } from '@/services/courseContextBuilder';
import { BlockType } from '@/types/page';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';

interface ExampleBlockEditorProps {
    courseContext: CourseContext;
    blockType: BlockType;
    initialContent?: string;
    onSave?: (content: string) => void;
}

/**
 * Example Block Editor with AI Assistant and Generation History
 */
export const ExampleBlockEditor: React.FC<ExampleBlockEditorProps> = ({
    courseContext,
    blockType,
    initialContent = '',
    onSave,
}) => {
    const [content, setContent] = useState<string>(initialContent);

    /**
     * Handle content generated by AI Assistant
     */
    const handleContentGenerated = (generatedContent: any) => {
        // Convert generated content to string if needed
        const contentText = typeof generatedContent === 'string'
            ? generatedContent
            : JSON.stringify(generatedContent, null, 2);

        setContent(contentText);
    };

    /**
     * Handle reusing content from history
     */
    const handleReuseFromHistory = (entry: GenerationHistoryEntry) => {
        // Convert entry content to string if needed
        const contentText = typeof entry.content === 'string'
            ? entry.content
            : JSON.stringify(entry.content, null, 2);

        setContent(contentText);
    };

    /**
     * Handle save
     */
    const handleSave = () => {
        if (onSave) {
            onSave(content);
        }
    };

    return (
        <div className="space-y-4">
            {/* Header with History Button */}
            <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">
                    Edit {blockType.charAt(0).toUpperCase() + blockType.slice(1)} Block
                </h2>

                <GenerationHistory
                    courseId={courseContext.courseId || 'default'}
                    onReuse={handleReuseFromHistory}
                />
            </div>

            {/* AI Assistant Panel */}
            <AIAssistantPanel
                blockType={blockType}
                courseContext={courseContext}
                onContentGenerated={handleContentGenerated}
                currentContent={content}
                placeholder={`Describe the ${blockType} content you want to generate...`}
            />

            {/* Content Editor */}
            <div className="space-y-2">
                <Label htmlFor="content-editor">Content</Label>
                <Textarea
                    id="content-editor"
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    placeholder={`Enter ${blockType} content...`}
                    rows={12}
                    className="font-mono text-sm"
                />
            </div>

            {/* Save Button */}
            <div className="flex justify-end">
                <button
                    onClick={handleSave}
                    className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
                >
                    Save Block
                </button>
            </div>
        </div>
    );
};

/**
 * Example Usage in a Page Editor
 */
export const ExamplePageEditor: React.FC = () => {
    const courseContext: CourseContext = {
        courseId: 'course-123',
        courseTitle: 'Introduction to Gamification',
        moduleId: 'module-1',
        moduleName: 'Getting Started',
        lessonId: 'lesson-1',
        lessonName: 'What is Gamification?',
        learningObjectives: [
            'Define gamification',
            'Understand key concepts',
            'Identify use cases',
        ],
        existingBlocks: [],
    };

    const handleSave = (content: string) => {
        console.log('Saving content:', content);
        // In a real implementation, this would save to the backend
    };

    return (
        <div className="container mx-auto p-6">
            <h1 className="text-2xl font-bold mb-6">Page Editor Example</h1>

            <ExampleBlockEditor
                courseContext={courseContext}
                blockType="text"
                onSave={handleSave}
            />
        </div>
    );
};

export default ExampleBlockEditor;
